<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Perch</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>&lt;perch:content(?:[^&gt;]*?)(?&lt;!/)&gt;</string>
			<key>name</key>
			<string>invalid.illegal.unclosed-self-closing-tag.perch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;perch:(?:if|help)(?:[^&gt;]*?)(?&lt;=/)&gt;</string>
			<key>name</key>
			<string>invalid.illegal.self-closed-block-level-tag.perch</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;perch:content</string>
			<key>end</key>
			<string>/&gt;</string>
			<key>name</key>
			<string>entity.name.tag.namespace.perch</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attribute-list</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;perch:(?:if|help)</string>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>entity.name.tag.namespace.perch</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attribute-list</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;/perch:(?:if|help)&gt;</string>
			<key>name</key>
			<string>entity.name.tag.namespace.perch</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute-list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.namespace.perch</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.perch</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+(?:=("[^"]*?"))?)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.xml.perch</string>
	<key>uuid</key>
	<string>CA2EAB8C-BB51-4D76-9763-87872A36358F</string>
</dict>
</plist>
